language: 'node_js'

node_js:
  - 'iojs'
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'
  - '9'

script:
  - 'npm run tests'
  - 'MAJOR_NODE_VERSION=${TRAVIS_NODE_VERSION:0:1}; if [ "${MAJOR_NODE_VERSION}" = "4" ]; then npm run lint; fi;
